### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by rcpinheiro** [lucasdupin/cordova-bring-to-front#2]
I got this error message when trying to install the plugin:

```
G:\Users\myser\work\app>cordova plugin add https://github.com/lucasdupin/cordova-bring-to-front.git
Failed to fetch plugin https://github.com/lucasdupin/cordova-bring-to-front.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! premature close
```
The debug log:
```
7 silly fetchPackageMetaData error for git+https://github.com/lucasdupin/cordova-bring-to-front.git premature close
8 timing stage:rollbackFailedOptional Completed in 0ms
9 timing stage:runTopLevelLifecycles Completed in 3818ms
10 verbose stack Error: premature close
10 verbose stack     at PassThrough.onclose (C:\Program Files\nodejs\node_modules\npm\node_modules\end-of-stream\index.js:47:67)
10 verbose stack     at PassThrough.emit (events.js:203:15)
10 verbose stack     at emitCloseNT (internal/streams/destroy.js:68:8)
10 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by DevelopersCourt** [comment]
Same problem.
